задачи по модулю 03
js-tasks-ru/nodejs-20220421_vs-oko pull request #3
Opened 2022-05-05 15:09 UTC by Dormeh

есть проблемы с похождением тестов в 03.04 и 03.05

2022-05-05 21:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-11 11:12 UTC, tadjik1 reviewed
Алексей, прекрасные решения и отличный код. Я отметил пару мест где нужны небольшие совсем доработки, но в целом все выполнено очень хорошо

2022-05-11 11:12 UTC, tadjik1 commented on 03-streams/04-file-server-post/server.js
> +    res.end('nested files are not supported');
Здесь нужен return, так как js не остановит выполнение функции в случае простого вызова res.end

2022-05-11 11:12 UTC, tadjik1 commented on 03-streams/04-file-server-post/server.js
> +          res.end(err.code);
После этого нужно также удалить файл, который был уже создан к этому моменту (частично)

2022-05-11 13:29 UTC, Dormeh commented on 03-streams/04-file-server-post/server.js
> +    res.end('nested files are not supported');
добавил

2022-05-11 13:29 UTC, Dormeh commented on 03-streams/04-file-server-post/server.js
> +          res.end(err.code);
добавил

2022-05-11 16:35 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2022-05-11 18:28 UTC, Dormeh commented
Сергей, возможно в погоне за прохождением тестов я что-то перемудрил. Посмотрите пожалуйста когда будет возможность.

2022-05-11 19:27 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-12 11:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-05-15 19:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-05-15 20:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-05-20 17:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-23 10:42 UTC, tadjik1 commented on 03-streams/04-file-server-post/server.js
> +          setTimeout(() => {
здесь не нужен `setTimeout`

2022-05-23 10:43 UTC, tadjik1 commented on 03-streams/04-file-server-post/server.js
> +      outStream.on('close', () => {
если вы обрабатываете это событие, то есть риск всегда вернуть 201 даже если была ошибка (что собственно в тестах и происходит). надежнее обрабатывать событие `finish`, оно сработает только если все прошло успешно

2022-05-23 10:43 UTC, tadjik1 requested changes
@Dormeh отметил в коде место, которое нужно поправить чтобы последний тест прошел. в остальном все выполнено очень хорошо 👍

2022-05-23 12:41 UTC, Dormeh commented on 03-streams/04-file-server-post/server.js
> +      outStream.on('close', () => {
у меня раньше так и было я исправил на 'close' так как от вас на занятии услышал что это самое правильная проверка на завершение.

2022-05-23 12:43 UTC, Dormeh commented on 03-streams/04-file-server-post/server.js
> +          setTimeout(() => {
это я для тестов делал чтобы статус не отдавало раньше `destroy()`,
но это не помогло в итоге оставил.

2022-05-23 12:45 UTC, Dormeh commented on 03-streams/04-file-server-post/server.js
> +      outStream.on('close', () => {
![image](https://user-images.githubusercontent.com/54811697/169822144-84287777-48a1-4c67-b0b4-53a26ac7f2dd.png)

2022-05-23 12:52 UTC, Dormeh commented
> @Dormeh отметил в коде место, которое нужно поправить чтобы последний тест прошел. в остальном все выполнено очень хорошо 👍

тесты локально все проходят кроме проверки на создание большого файла в 03.04  и к сожалению это никак не влияет хоть 'finish' хоть 'close', но из-за того что обработчик стоит на 'close' сервер тестовый не мог завершить работу и висел.
Исправил код по вашим замечаниям.

2022-05-23 13:00 UTC, Dormeh commented on 03-streams/04-file-server-post/server.js
> +      outStream.on('close', () => {
поменял

2022-05-23 13:00 UTC, Dormeh commented on 03-streams/04-file-server-post/server.js
> +          setTimeout(() => {
удалил setTimeout

2022-05-23 13:07 UTC, Dormeh commented
@tadjik1  Сергей, обратите внимание на задачу 05.
сервер на тестах висит и не завершается.

2022-05-23 18:56 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-23 22:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-24 15:51 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-24 21:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-27 02:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-27 11:11 UTC, tadjik1 approved these changes
Предлагаю ПР замержить (так как все сделано верно), параллельно я попробую разобраться что не так с тестами

2022-05-27 11:13 UTC, merged

2022-05-27 11:22 UTC, Dormeh commented
🎉